### ISSUE TITLE
Temperature is in between min and max, but blinds are fully closed

### ISSUE THREAD

**Issue by Dielee** [basbruss/adaptive-cover#203]
### What version of Adaptive Cover are you using?

v1.2.2

### What version of Home Assistant are you using?

2024.6.0

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Hello! 
first, thanks for your effort and this integration. 

The temperature from the sensor entity (21,4) is between min (18) and max (23,5).
So, what the flow looks like, the blind should be opend, but they are closed. 
Not 0%, but 4%, 6% and so on...I don't understand why the shutters are closed.
Maybe this isn't a bug, just an understanding question.

![2024-06-07 08_45_03-Einstellungen – Home Assistant](https://github.com/basbruss/adaptive-cover/assets/45101649/b6a3a4a5-648e-4e32-a6c0-9835a2ee7ea6)
![2024-06-07 08_45_08-Einstellungen – Home Assistant](https://github.com/basbruss/adaptive-cover/assets/45101649/42a62123-f8b4-4010-a97c-bebaba5f2cca)
![2024-06-07 08_45_30-Einstellungen – Home Assistant](https://github.com/basbruss/adaptive-cover/assets/45101649/aba3ed72-2503-4ac2-a67d-4f379d605570)
![2024-06-07 08_46_19-Einstellungen – Home Assistant](https://github.com/basbruss/adaptive-cover/assets/45101649/16be230d-4580-44c9-8550-b4ad04a65d42)

### Reproduction steps

1. Activate climate mode
2. Input sensor entity for inside temp
3. Set min and max in between the inside temp
4. Covers should be open

**Comment by basbruss** [comment]
So the cover is not adjusted to the calculated position of the sensor? It can be the `end_time`, `minimum delta between position changes`.

See also this issue #202

**Comment by Dielee** [comment]
No, this works. But shouldn't stay the cover open in between the min and max temp ?

**Comment by basbruss** [comment]
Yes, when presence is detected or no presence sensor is set, our only goal in the intermediate mode is to reduce glare while letting in valuable natural light. This holds for all three temperature modes with presence. 
Fully closed is never the wanted strategy if the sun is in front of the window and there is presence because this integration is built around the principle that we want as much natural light as possible while reducing glare and direct light on our workspaces/into our rooms

**Comment by Dielee** [comment]
There is no presence set at this time. At this time the room is dark and temperature is in between min and max. So what can i do ?

**Comment by basbruss** [comment]
Just to understand things better.
Do you have shutters like  `Rollläden` that do not directly open? Does the position of the sensor correspond with the position of the cover entity?

> There is no presence set at this time

What do you mean by this?
 1. no presence entity is configured
 2. Presence is not detected

**Comment by Dielee** [comment]
I have shutters which are closed, if the room temperature is in between min an max temp. 
The position of the sensor correspond with the position, yes.

1. It is no presence entity configured

**Comment by basbruss** [comment]
Does it work when you toggle the climate mode off?

**Comment by Dielee** [comment]
I can't test now, as the sun isn't in front of my window anymore. So there are at 100% now...

**Comment by basbruss** [comment]
Okay, I think if have reproduced a similar looking issue. Can it be that your default position is 0%? Because I do get the default position in that situation where actually the calculated position is expected.

**Comment by Dielee** [comment]
No, default is 100%. Maybe i'm able to reproduce with another group of adaptive covers. Should i try?

**Comment by basbruss** [comment]
Yes, please also share as many of your settings, so I can reproduce it. (future releases will enable diagnostics download from HA to include all the settings)

**Comment by Dielee** [comment]
Okay, i will try! Give me some time

**Comment by Dielee** [comment]
I rebuild this issue for my south windows and it's the same. 
Here are my settings:

![2024-06-07 13_24_03-Übersicht – Home Assistant](https://github.com/basbruss/adaptive-cover/assets/45101649/a7912b15-3a6b-4c30-959d-81b726bdb400)
![2024-06-07 13_24_59-Einstellungen – Home Assistant](https://github.com/basbruss/adaptive-cover/assets/45101649/eeba237f-c2e9-4a8b-a535-4ddad0618540)
![2024-06-07 13_25_12-Einstellungen – Home Assistant](https://github.com/basbruss/adaptive-cover/assets/45101649/da2edd30-c627-4eb0-ac4f-efc2c2aa9e9f)
![2024-06-07 13_25_21-Einstellungen – Home Assistant](https://github.com/basbruss/adaptive-cover/assets/45101649/3bde8a2c-f140-4b49-8124-16bef1c7d208)
![2024-06-07 13_25_36-Einstellungen – Home Assistant](https://github.com/basbruss/adaptive-cover/assets/45101649/abdebeaf-70db-41e3-a562-6c9f5dc8012c)
![2024-06-07 13_25_49-Einstellungen – Home Assistant](https://github.com/basbruss/adaptive-cover/assets/45101649/d0336bdd-9af6-439d-b033-57c49453acbd)
![2024-06-07 13_26_09-Entwicklerwerkzeuge – Home Assistant](https://github.com/basbruss/adaptive-cover/assets/45101649/0a471e9b-ce13-4d71-b11f-292d5463763a)

**Comment by Dielee** [comment]
Current service state:

![2024-06-07 13_28_46-Einstellungen – Home Assistant](https://github.com/basbruss/adaptive-cover/assets/45101649/4ddeed14-b529-4ef7-857f-691a726e5737)

**Comment by basbruss** [comment]
Okay, this clears some things up for me. So first of all the change in the position of the sensor must be at least 10% higher/lower than the cover currently is. So cover at 0% and sensor to 10% results in cover to 10%, but cover at 0% and sensor to 9% results in cover to 0%.

Secondly, the distance  (`shaded area`) is 0.1m to the workspace from the cover. This is very low and translates to that we only let in light if the elevation angle is very steep, hence the calculated position is very low. Which corresponds to the actual sensor state. The lower the elevation angle of the sun, the lower the cover must be to block out direct light on a workspace surface 10 centimetres from the window.

So I don't think this is a bug for now, but rather a misunderstanding of the mechanics and algorithm used.

You could increase the distance (`shaded area`) since the height of the surface plane is equal to the bottom of the window, so 0.5m will in most cases not produce glare to your eyes.

**Comment by Dielee** [comment]
Ah alright! But i don't understand `shaded area`, maybe i am just dump ?....
I changed to 0,5 and it works now. Thanks!

**Comment by Dielee** [comment]
But, are the covers normaly not fully openend when temperature is in between min and max ?

**Comment by basbruss** [comment]
> But, are the covers normaly not fully openend when temperature is in between min and max ?

No, since this integration aims to reduce visible glare to occupants while maximizing natural light coming in. Fully open with presence will lead to disturbing glare. If you want to understand it better I highly recommend reading this [paper](https://www.mdpi.com/1996-1073/13/7/1731), although it is aimed to tilted blinds, the same principles hold for covers in general, be it that the calculation of the angles is slightly different.

**Comment by Dielee** [comment]
Ahhh, great! This makes sence. Thanks for your patience!
