### ISSUE TITLE
Fully close screens

### ISSUE THREAD

**Issue by snoekieboe** [basbruss/adaptive-cover#230]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Regardeless of the configuration i make, i cannot get my screens to close fully. They always remain open 2 or 3 percent. This causes false states in my other automations that depend on the screens state being "open" or "closed". These states are never reached as the screens remain open a few percent when controlled by the "Adaptive Cover addon"

i've tinkered with the window dimensions an work area (curently i have my window height set at 2.3 meter and the work area set to 0.1). But since the work area lowest settings allowed is 0.1 i cannot seem to reach a fully closed state for my screens.

### Describe the solution you'd like

I would like th Adaptive Cover Addon to be able to fully close my screens. If my insights are right, allowing "work area configuration" to 0 as the lowest setting would fix my issue.

### Describe alternatives you've considered

Don't know, open to suggestions

### Additional context

Sorry no additional context

**Comment by basbruss** [comment]
Can you download the diagnostics from the integration tab, so I can evaluate your device settings? Usually without setting one of the defaults to 0 the cover doesn't have to fully close, since this is only needed when the sun is at a very low elevation (just above 0).

**Comment by snoekieboe** [comment]
[config_entry-adaptive_cover-27ab917902309cc986bdf51555def5a7.json](https://github.com/user-attachments/files/15911545/config_entry-adaptive_cover-27ab917902309cc986bdf51555def5a7.json)
Sure! here you go :-) Thank you for wanting to look into this

**Comment by basbruss** [comment]
As expected none of your defaults are set to zero. So it is actually not expected to reach 0% since the formulas try to optimize the opening position without letting in unwanted glare. 

The work area cannot be 0 since this messes up the calculations and it is also not recommended to set it as low as possible.

> (curently i have my window height set at 2.3 meter and the work area set to 0.1)

According to your trace you have set the window height to 6 meters. Please give the actual height of the window or the length of the cover between 0% and 100% open.

**Comment by snoekieboe** [comment]
Thanks for your swift reply. The 6 meter window height is probably due to playing around a bit. The screen also never reaches zero if i set it the actual height (2.3 meters). Which other default not being set to zero are you referring to?

And what is the argument behind "and it is also not recommended to set it as low as possible". just trying to understand how the logic was meant to work :-)

**Comment by basbruss** [comment]
You have the default and (after) sunset default values that you can set.

This post provides more details on how the system works: https://community.home-assistant.io/t/automatic-blinds-sunscreen-control-based-on-sun-platform/573818. Essentially, having a lower distance to the work area is usually inaccurate because most people don't sit as close as 10 centimeters from the window. Setting this distance to zero will result in the cover always being at 0%, as the corner of the geometric triangle is directly at the window, causing the elevation to be effectively ignored in the calculations.

**Comment by snoekieboe** [comment]
Aaah i see.. and understand now. My use case seems to differ from what the Add on was intended for. The add on seems to focus on preventing glare primarily.. i want to control indoor temperature primarily instead. My windows also stretch from the ceiling all the way to the floor..

I can live with the screens not being close fully though, just need to figur out a way to reflect the closed state when they are actually still open 1 or 2 %.

Thanks for your help!

**Comment by basbruss** [comment]
If you want to control the indoor temperature you can enable the climate mode. That tries to find an optimal solution between indoor temperature and reducing glare while someone is present.

**Comment by snoekieboe** [comment]
Did that in the mean time.. works a charm.. love your work.. keep it up!
