### ISSUE TITLE
Distance to shaded area not taking length of horizontal awning into account 

### ISSUE THREAD

**Issue by Appesteijn** [basbruss/adaptive-cover#258]
### What version of Adaptive Cover are you using?

1.3.2

### What version of Home Assistant are you using?

2024.7.2

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I tried to find the code, but my coding is a little bit rusty. I have the feeling that 'distance to shaded area' doesn't take an extending horizontal awning into account. 
For horizontal shades the distance is constant and stay's the same, but an extending awning should add the current extend (percentage_closed * awning_length) into the calculation.

### Reproduction steps

When sun still reaches your 'shaded area', increase the 'distance to shaded area' in the config.

**Comment by basbruss** [comment]
The distance parameter remains constant in all scenarios because it measures the distance from the window or cover to the specified shaded area, as indicated by the orange line in the diagram.
![horizontal_cover](https://github.com/user-attachments/assets/27382dce-50ac-417d-a914-5ce8855ce393)

The percentage is determined using the maximum awning length. This length is adjusted using geometric calculations to account for different angles relative to a vertical blind. The length of the vertical blind, based on the sun's position, is then converted back to the length of a horizontal cover using these geometric principles.

For more details, you can check the related code here:
https://github.com/basbruss/adaptive-cover/blob/07b235edb1210aa89fd8cb3b87ff48e750101d52/custom_components/adaptive_cover/calculation.py#L426-L442

**Comment by Appesteijn** [comment]
Thank you!

**Comment by Appesteijn** [comment]
I was too fast. With these settings
![Screenshot_20240719-173348](https://github.com/user-attachments/assets/30f8115a-ac3c-4324-b256-212a166fea9b)

I get this:
![IMG_20240719_172537420](https://github.com/user-attachments/assets/e560c8b9-3073-4126-b560-f5ce0c5b0c93)

I would expect it to be:
![IMG_20240719_172858752](https://github.com/user-attachments/assets/0fb55e8f-4f21-4157-99f4-5ddc226a12d5)

What am I doing wrong? :)

**Comment by basbruss** [comment]
Can you share the diagnostics dump from the integration tab and maybe add some debug logs from the integration?
There are just too many parameters that can influence the actual position.

**Comment by Appesteijn** [comment]
When I change the 'Shaded area' to 2 meters, the extension is correct.

**Comment by basbruss** [comment]
What are the percentages that HA shows when the awning is fully opened and fully closed? I suspect it's the inverse of the general HA convention that is used for covers, where 100% is fully open/extended and 0% is fully closed/not extended.

**Comment by Appesteijn** [comment]
100% is open or up, 0% is closed or down.

**Comment by basbruss** [comment]
Seems indeed the opposite as is assumed within the integration for horizontal covers. You can use the inverse option in the options menu.

**Comment by Appesteijn** [comment]
Is it also for vertical covers? 100% is open and 0% is closed?

**Comment by Appesteijn** [comment]
I'll test tomorrow and will close this ticket when it works. Thank you for you fast response and help!

**Comment by Appesteijn** [comment]
Looks like this was the solution. The percentage should be interpreted as '% closed'. I though it was '% open'
